spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties: # property ?? ??
      hibernate: # hibernate property ??
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /h2-console
      enabled: true